DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;

CREATE TABLE ARTISTS (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE ALBUMS (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  genre VARCHAR(255),
  artist_id INT REFERENCES artists(id) NOT NULL
);
